# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{json_record}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Durand"]
  s.date = %q{2011-07-07}
  s.email = %q{brian@embellishedvisions.com}
  s.extra_rdoc_files = [
    "MIT_LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "MIT_LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/json_record.rb",
    "lib/json_record/attribute_methods.rb",
    "lib/json_record/embedded_document.rb",
    "lib/json_record/embedded_document_array.rb",
    "lib/json_record/field_definition.rb",
    "lib/json_record/json_field.rb",
    "lib/json_record/schema.rb",
    "lib/json_record/serialized.rb",
    "spec/embedded_document_array_spec.rb",
    "spec/embedded_document_spec.rb",
    "spec/field_definition_spec.rb",
    "spec/serialized_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_models.rb"
  ]
  s.homepage = %q{http://github.com/bdurand/json_record}
  s.rdoc_options = ["--charset=UTF-8", "--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{ActiveRecord support for mapping complex documents in a single RDBMS row via JSON serialization.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

